server:
  port:
    8082
spring:
  application:
    name: orchestrator
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
eureka:
  client:
    server-url:
      defaultZone: http:localhost:8761/eureka