services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: Video-Editor
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    image: auth-service:latest
    ports:
      - "8087:8087"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql

  api-gateway-service:
    image: api-gateway-service:latest
    ports:
      - "8088:8088"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-service

  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"

  orchestrator-service:
    image: orchestrator-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - auth-service

  presigned-url-service:
    image: presigned-url-service:latest
    ports:
      - "8083:8083"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - auth-service
      - orchestrator-service

  download-files-service:
    image: download-files-service:latest
    ports:
      - "8085:8085"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - /home/aritra/Desktop:/app/downloads
    depends_on:
      - auth-service
      - orchestrator-service
      - presigned-url-service

  build-command-service:
    image: build-command-service:latest
    ports:
      - "8086:8086"
    depends_on:
      - auth-service
      - orchestrator-service
      - eureka-server

  input-processing-service:
    image: input-processing-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - orchestrator-service
      - eureka-server

  filter-complex-service:
    image: filter-complex-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
      - orchestrator-service
      - eureka-server
  execute-command-service:
    image: execute-command-service:latest
    ports:
      - "8084:8084"
    volumes:
      - /home/aritra/Desktop:/app/downloads
    depends_on:
      - auth-service
      - orchestrator-service
      - eureka-server
volumes:
  mysql-data: