version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: Video-Editor
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build: ./auth-service
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql

  gateway:
    build: ./api-gateway
    ports:
      - "8088:8088"
    depends_on:
      - auth-service

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  orchestrator-service:
    build: ./orchestrator-service
    depends_on:
        - auth-service

  presigned-url-service:
    build: ./presigned-url-service
    depends_on:
      - auth-service
      - orchestrator-service

  upload-service:
    build: ./upload-service
    depends_on:
      - auth-service
      - orchestrator-service
      - presigned-url-service

  download-files-service:
    build: ./download-files-service
    depends_on:
      - auth-service
      - orchestrator-service
      - presigned-url-service

  build-command-service:
    build: ./build-command-service
    depends_on:
      - auth-service
      - orchestrator-service
      - eureka-server

  input-processing-service:
    build: ./input-processing-service
    depends_on:
      - auth-service
      - orchestrator-service
      - eureka-server

  filter-complex-service:
    build: ./filter-complex-service
    depends_on:
      - auth-service
      - orchestrator-service
      - eureka-server

volumes:
  mysql-data:
