server:
  port: 8086
spring:
  application:
    name: build-command
  rabbitmq:
    host: rabbitmq
    port: 5672
  redis:
    host: redis
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

