server:
  port: 8089
spring:
  application:
    name: project
  datasource:
    url: jdbc:mysql://mysql:3306/Project-DB
    username: root
    password: my_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    config:
      import: "optional:env[.env]"
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/