server:
  port: 8080

spring:
  application:
    name: input-processing
  rabbitmq:
    host: rabbitmq
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

