server:
  port: 8081

spring:
  application:
    name: filter-complex
  rabbitmq:
    host: rabbitmq
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
