server:
  port:
    8083
spring:
  application:
    name: presigned-url
  rabbitmq:
    host: rabbitmq
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
