server:
  port:
    8083
spring:
  application:
    name: upload-video
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    server-url:
      defaultZone: http:localhost:8761/eureka