server:
  port: 8088

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:3000,http://127.0.0.1:3001,https://video-editor-phi-eight.vercel.app"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: auth-service-signup
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/signup
        - id: auth-service-login
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/login
        - id: orchestrator
          uri: lb://ORCHESTRATOR
          predicates:
            - Path=/api/v1/process/**
          filters:
            - JwtAuthFilter
        - id: presigned-url
          uri: lb://PRESIGNED-URL
          predicates:
            - Path=/api/v1/presigned-urls/**
          filters:
            - JwtAuthFilter
        - id: project-service
          uri: lb://PROJECT
          predicates:
            - Path=/api/v1/project/**
          filters:
            - JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
