server:
  port: 8088

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service-signup
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/signup
        - id: auth-service-login
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/login
        - id: orchestrator
          uri: lb://ORCHESTRATOR
          predicates:
            - Path=/api/v1/process/**
          filters:
            - JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
